import { getDb } from "../src/db";
import { videos } from "../src/db/schema";

const db = getDb();

const newVideosData = [
  {
    youtubeId: "QFDBeGQILzY",
    title: "Sexy Media Full Show Day 1",
    thumbnailUrl: "https://i.ytimg.com/vi/QFDBeGQILzY/hqdefault.jpg",
    channelId: "sexymedia",
    channelTitle: "Sexy Media",
    category: "swimwear",
    isFeatured: false,
    sortOrder: 26,
  },
  {
    youtubeId: "Y1vyiIpJhHA",
    title: "Sexy Media Full Show Day 2",
    thumbnailUrl: "https://i.ytimg.com/vi/Y1vyiIpJhHA/hqdefault.jpg",
    channelId: "sexymedia",
    channelTitle: "Sexy Media",
    category: "swimwear",
    isFeatured: false,
    sortOrder: 27,
  },
  {
    youtubeId: "Cc0N7a-eCZw",
    title: "Miami Swim Week TV - EXA Swim",
    thumbnailUrl: "https://i.ytimg.com/vi/Cc0N7a-eCZw/hqdefault.jpg",
    channelId: "miamiswimweektv",
    channelTitle: "Miami Swim Week TV",
    category: "swimwear",
    isFeatured: false,
    sortOrder: 28,
  },
  {
    youtubeId: "yU6lVxgVAfU",
    title: "Miami Swim Week TV - Pia Bolte",
    thumbnailUrl: "https://i.ytimg.com/vi/yU6lVxgVAfU/hqdefault.jpg",
    channelId: "miamiswimweektv",
    channelTitle: "Miami Swim Week TV",
    category: "swimwear",
    isFeatured: false,
    sortOrder: 29,
  },
  {
    youtubeId: "CyXsa4-yi7U",
    title: "Miami Swim Week TV - Super",
    thumbnailUrl: "https://i.ytimg.com/vi/CyXsa4-yi7U/hqdefault.jpg",
    channelId: "miamiswimweektv",
    channelTitle: "Miami Swim Week TV",
    category: "swimwear",
    isFeatured: false,
    sortOrder: 30,
  },
  {
    youtubeId: "A5oiq5XhylI",
    title: "Miami Swim Week TV - Mariella Swim",
    thumbnailUrl: "https://i.ytimg.com/vi/A5oiq5XhylI/hqdefault.jpg",
    channelId: "miamiswimweektv",
    channelTitle: "Miami Swim Week TV",
    category: "swimwear",
    isFeatured: false,
    sortOrder: 31,
  },
  {
    youtubeId: "00aJzz0qEcA",
    title: "Miami Swim Week TV - Veve",
    thumbnailUrl: "https://i.ytimg.com/vi/00aJzz0qEcA/hqdefault.jpg",
    channelId: "miamiswimweektv",
    channelTitle: "Miami Swim Week TV",
    category: "swimwear",
    isFeatured: false,
    sortOrder: 32,
  },
  {
    youtubeId: "x4AB3dFsMKs",
    title: "Miami Swim Week TV - Bikini Flavors",
    thumbnailUrl: "https://i.ytimg.com/vi/x4AB3dFsMKs/hqdefault.jpg",
    channelId: "miamiswimweektv",
    channelTitle: "Miami Swim Week TV",
    category: "swimwear",
    isFeatured: false,
    sortOrder: 33,
  },
  {
    youtubeId: "K0egMLGe0so",
    title: "Miami Swim Week TV - Karen",
    thumbnailUrl: "https://i.ytimg.com/vi/K0egMLGe0so/hqdefault.jpg",
    channelId: "miamiswimweektv",
    channelTitle: "Miami Swim Week TV",
    category: "swimwear",
    isFeatured: false,
    sortOrder: 34,
  },
  {
    youtubeId: "LRzzpEl7kiU",
    title: "Miami Swim Week TV - Sherbert Lemons",
    thumbnailUrl: "https://i.ytimg.com/vi/LRzzpEl7kiU/hqdefault.jpg",
    channelId: "miamiswimweektv",
    channelTitle: "Miami Swim Week TV",
    category: "swimwear",
    isFeatured: false,
    sortOrder: 35,
  },
  {
    youtubeId: "Kowpi6S7UO0",
    title: "Miami Swim Week TV - Bronzed",
    thumbnailUrl: "https://i.ytimg.com/vi/Kowpi6S7UO0/hqdefault.jpg",
    channelId: "miamiswimweektv",
    channelTitle: "Miami Swim Week TV",
    category: "swimwear",
    isFeatured: false,
    sortOrder: 36,
  },
  {
    youtubeId: "mU0A202Dik8",
    title: "Miami Swim Week TV - Capristan",
    thumbnailUrl: "https://i.ytimg.com/vi/mU0A202Dik8/hqdefault.jpg",
    channelId: "miamiswimweektv",
    channelTitle: "Miami Swim Week TV",
    category: "swimwear",
    isFeatured: false,
    sortOrder: 37,
  },
  {
    youtubeId: "PTaE4eTGAWg",
    title: "Jeff Sarita Photography - Capristan",
    thumbnailUrl: "https://i.ytimg.com/vi/PTaE4eTGAWg/hqdefault.jpg",
    channelId: "jeffsaritaphotography",
    channelTitle: "Jeff Sarita Photography",
    category: "swimwear",
    isFeatured: false,
    sortOrder: 38,
  },
  {
    youtubeId: "6m3C7xIPB4A",
    title: "Jeff Sarita Photography - Super",
    thumbnailUrl: "https://i.ytimg.com/vi/6m3C7xIPB4A/hqdefault.jpg",
    channelId: "jeffsaritaphotography",
    channelTitle: "Jeff Sarita Photography",
    category: "swimwear",
    isFeatured: false,
    sortOrder: 39,
  },
  {
    youtubeId: "JZNTZsJDKuI",
    title: "Jeff Sarita Photography - Mariella",
    thumbnailUrl: "https://i.ytimg.com/vi/JZNTZsJDKuI/hqdefault.jpg",
    channelId: "jeffsaritaphotography",
    channelTitle: "Jeff Sarita Photography",
    category: "swimwear",
    isFeatured: false,
    sortOrder: 40,
  },
  {
    youtubeId: "wFvgmtTRbGo",
    title: "Zexy Baddies - Super",
    thumbnailUrl: "https://i.ytimg.com/vi/wFvgmtTRbGo/hqdefault.jpg",
    channelId: "zexybaddies",
    channelTitle: "Zexy Baddies",
    category: "swimwear",
    isFeatured: false,
    sortOrder: 41,
  },
  {
    youtubeId: "vdt1lbuJC24",
    title: "Zexy Baddies - Sewhi",
    thumbnailUrl: "https://i.ytimg.com/vi/vdt1lbuJC24/hqdefault.jpg",
    channelId: "zexybaddies",
    channelTitle: "Zexy Baddies",
    category: "swimwear",
    isFeatured: false,
    sortOrder: 42,
  },
  {
    youtubeId: "WGbjoyq09H0",
    title: "Zexy Baddies - Casting Call",
    thumbnailUrl: "https://i.ytimg.com/vi/WGbjoyq09H0/hqdefault.jpg",
    channelId: "zexybaddies",
    channelTitle: "Zexy Baddies",
    category: "swimwear",
    isFeatured: false,
    sortOrder: 43,
  },
  {
    youtubeId: "LyMckCEBd4A",
    title: "Projet Nu - EXA Swim",
    thumbnailUrl: "https://i.ytimg.com/vi/LyMckCEBd4A/hqdefault.jpg",
    channelId: "projetnu",
    channelTitle: "Projet Nu",
    category: "swimwear",
    isFeatured: false,
    sortOrder: 44,
  },
  {
    youtubeId: "g2Il6jXLwRw",
    title: "Projet Nu - Golden",
    thumbnailUrl: "https://i.ytimg.com/vi/g2Il6jXLwRw/hqdefault.jpg",
    channelId: "projetnu",
    channelTitle: "Projet Nu",
    category: "swimwear",
    isFeatured: false,
    sortOrder: 45,
  },
  {
    youtubeId: "bYzzNSEEKuM",
    title: "Projet Nu - Sewhi",
    thumbnailUrl: "https://i.ytimg.com/vi/bYzzNSEEKuM/hqdefault.jpg",
    channelId: "projetnu",
    channelTitle: "Projet Nu",
    category: "swimwear",
    isFeatured: false,
    sortOrder: 46,
  },
  {
    youtubeId: "VykF9PVNXHk",
    title: "Projet Nu - Bronzed",
    thumbnailUrl: "https://i.ytimg.com/vi/VykF9PVNXHk/hqdefault.jpg",
    channelId: "projetnu",
    channelTitle: "Projet Nu",
    category: "swimwear",
    isFeatured: false,
    sortOrder: 47,
  },
  {
    youtubeId: "72wRZWY8SRE",
    title: "Projet Nu - Suzu",
    thumbnailUrl: "https://i.ytimg.com/vi/72wRZWY8SRE/hqdefault.jpg",
    channelId: "projetnu",
    channelTitle: "Projet Nu",
    category: "swimwear",
    isFeatured: false,
    sortOrder: 48,
  },
  {
    youtubeId: "X9kA6BWWY2c",
    title: "Projet Nu - Capristan",
    thumbnailUrl: "https://i.ytimg.com/vi/X9kA6BWWY2c/hqdefault.jpg",
    channelId: "projetnu",
    channelTitle: "Projet Nu",
    category: "swimwear",
    isFeatured: false,
    sortOrder: 49,
  },
  {
    youtubeId: "0OhZp4FSiMU",
    title: "Projet Nu - Origin",
    thumbnailUrl: "https://i.ytimg.com/vi/0OhZp4FSiMU/hqdefault.jpg",
    channelId: "projetnu",
    channelTitle: "Projet Nu",
    category: "swimwear",
    isFeatured: false,
    sortOrder: 50,
  },
  {
    youtubeId: "aSo3-aF0ERQ",
    title: "Projet Nu - Mariella",
    thumbnailUrl: "https://i.ytimg.com/vi/aSo3-aF0ERQ/hqdefault.jpg",
    channelId: "projetnu",
    channelTitle: "Projet Nu",
    category: "swimwear",
    isFeatured: false,
    sortOrder: 51,
  },
  {
    youtubeId: "lYzSnPZ-peE",
    title: "Projet Nu - Super",
    thumbnailUrl: "https://i.ytimg.com/vi/lYzSnPZ-peE/hqdefault.jpg",
    channelId: "projetnu",
    channelTitle: "Projet Nu",
    category: "swimwear",
    isFeatured: false,
    sortOrder: 52,
  },
  {
    youtubeId: "Qxi9oHMvrH8",
    title: "Projet Nu - Veve",
    thumbnailUrl: "https://i.ytimg.com/vi/Qxi9oHMvrH8/hqdefault.jpg",
    channelId: "projetnu",
    channelTitle: "Projet Nu",
    category: "swimwear",
    isFeatured: false,
    sortOrder: 53,
  },
  {
    youtubeId: "urjn8b1O5Wk",
    title: "Projet Nu - Gari Fashion",
    thumbnailUrl: "https://i.ytimg.com/vi/urjn8b1O5Wk/hqdefault.jpg",
    channelId: "projetnu",
    channelTitle: "Projet Nu",
    category: "swimwear",
    isFeatured: false,
    sortOrder: 54,
  },
  {
    youtubeId: "ns1wW6t2ZQs",
    title: "Projet Nu - Sugarbush",
    thumbnailUrl: "https://i.ytimg.com/vi/ns1wW6t2ZQs/hqdefault.jpg",
    channelId: "projetnu",
    channelTitle: "Projet Nu",
    category: "swimwear",
    isFeatured: false,
    sortOrder: 55,
  },
  {
    youtubeId: "tUzkvoJsiRU",
    title: "Evoke Channel - Casting Call",
    thumbnailUrl: "https://i.ytimg.com/vi/tUzkvoJsiRU/hqdefault.jpg",
    channelId: "evokechannel",
    channelTitle: "Evoke Channel",
    category: "swimwear",
    isFeatured: false,
    sortOrder: 56,
  },
  {
    youtubeId: "rufD0qzE77I",
    title: "Photomeike - Bronzed Babe",
    thumbnailUrl: "https://i.ytimg.com/vi/rufD0qzE77I/hqdefault.jpg",
    channelId: "photomeike",
    channelTitle: "Photomeike",
    category: "swimwear",
    isFeatured: false,
    sortOrder: 57,
  },
  {
    youtubeId: "GR26qaWnZFI",
    title: "Photomeike - Mariella Swim",
    thumbnailUrl: "https://i.ytimg.com/vi/GR26qaWnZFI/hqdefault.jpg",
    channelId: "photomeike",
    channelTitle: "Photomeike",
    category: "swimwear",
    isFeatured: false,
    sortOrder: 58,
  },
  {
    youtubeId: "onz6kpDmO3g",
    title: "JemiibyDQ - Suzu",
    thumbnailUrl: "https://i.ytimg.com/vi/onz6kpDmO3g/hqdefault.jpg",
    channelId: "jemiibydq",
    channelTitle: "JemiibyDQ",
    category: "swimwear",
    isFeatured: false,
    sortOrder: 59,
  },
  {
    youtubeId: "ttK5mMYTkQA",
    title: "Heat Pop - Sherbert Lemons @ The Moore",
    thumbnailUrl: "https://i.ytimg.com/vi/ttK5mMYTkQA/hqdefault.jpg",
    channelId: "heatpop",
    channelTitle: "Heat Pop",
    category: "swimwear",
    isFeatured: false,
    sortOrder: 60,
  },
  {
    youtubeId: "xQ-sDj8CK-A",
    title: "Heat Pop - EXA Swim @ The Moore",
    thumbnailUrl: "https://i.ytimg.com/vi/xQ-sDj8CK-A/hqdefault.jpg",
    channelId: "heatpop",
    channelTitle: "Heat Pop",
    category: "swimwear",
    isFeatured: false,
    sortOrder: 61,
  },
  {
    youtubeId: "9RFm_jgvjK4",
    title: "Kevin B Johnson - Goalden Swimwear",
    thumbnailUrl: "https://i.ytimg.com/vi/9RFm_jgvjK4/hqdefault.jpg",
    channelId: "kevinbjohnson",
    channelTitle: "Kevin B Johnson",
    category: "swimwear",
    isFeatured: false,
    sortOrder: 62,
  },
  {
    youtubeId: "TEqGkid7M7o",
    title: "Kevin B Johnson - Marielle Swim",
    thumbnailUrl: "https://i.ytimg.com/vi/TEqGkid7M7o/hqdefault.jpg",
    channelId: "kevinbjohnson",
    channelTitle: "Kevin B Johnson",
    category: "swimwear",
    isFeatured: false,
    sortOrder: 63,
  },
  {
    youtubeId: "iY8oHBP0czU",
    title: "Shot by Townes - Super",
    thumbnailUrl: "https://i.ytimg.com/vi/iY8oHBP0czU/hqdefault.jpg",
    channelId: "shotbytownes",
    channelTitle: "Shot by Townes",
    category: "swimwear",
    isFeatured: false,
    sortOrder: 64,
  },
  {
    youtubeId: "MwD0IK_NEqs",
    title: "Shot by Townes - Suzu",
    thumbnailUrl: "https://i.ytimg.com/vi/MwD0IK_NEqs/hqdefault.jpg",
    channelId: "shotbytownes",
    channelTitle: "Shot by Townes",
    category: "swimwear",
    isFeatured: false,
    sortOrder: 65,
  },
  {
    youtubeId: "faAncNuyjCY",
    title: "NewYorkFashionTimes",
    thumbnailUrl: "https://i.ytimg.com/vi/faAncNuyjCY/hqdefault.jpg",
    channelId: "newyorkfashiontimes",
    channelTitle: "NewYorkFashionTimes",
    category: "swimwear",
    isFeatured: false,
    sortOrder: 66,
  },
];

async function addNewVideos() {
  console.log("Adding new videos...\n");

  let added = 0;
  let updated = 0;

  for (const video of newVideosData) {
    try {
      const result = await db
        .insert(videos)
        .values(video)
        .onConflictDoUpdate({
          target: videos.youtubeId,
          set: {
            title: video.title,
            thumbnailUrl: video.thumbnailUrl,
            channelId: video.channelId,
            channelTitle: video.channelTitle,
            sortOrder: video.sortOrder,
            updatedAt: new Date(),
          },
        });
      console.log(`✓ ${video.title}`);
      added++;
    } catch (error) {
      console.error(`✗ Failed: ${video.title}`, error);
    }
  }

  console.log(`\nDone! Processed ${added} videos`);
  process.exit(0);
}

addNewVideos();
