import { getDb } from "../src/db";
import { videos } from "../src/db/schema";

const db = getDb();

const videosData = [
  {
    youtubeId: "ll1TPIm_XlQ",
    title: "IVY Swimwear | Fashion Runway Full Show",
    thumbnailUrl: "https://i.ytimg.com/vi/ll1TPIm_XlQ/hqdefault.jpg",
    channelId: "alainmoise",
    channelTitle: "Alain Moise",
    category: "swimwear",
    isFeatured: true,
    sortOrder: 1,
  },
  {
    youtubeId: "XEFJeKq4o2I",
    title: "BAY Swimwear | Fashion Runway Full Show",
    thumbnailUrl: "https://i.ytimg.com/vi/XEFJeKq4o2I/hqdefault.jpg",
    channelId: "alainmoise",
    channelTitle: "Alain Moise",
    category: "swimwear",
    isFeatured: true,
    sortOrder: 2,
  },
  {
    youtubeId: "p2neBy7V-mY",
    title: "Berry Beachy Swimwear | Fashion Runway Full Show",
    thumbnailUrl: "https://i.ytimg.com/vi/p2neBy7V-mY/hqdefault.jpg",
    channelId: "alainmoise",
    channelTitle: "Alain Moise",
    category: "swimwear",
    isFeatured: true,
    sortOrder: 3,
  },
  {
    youtubeId: "TnoZi5vL7Vk",
    title: "Exa Swimwear 4K | Fashion Runway Full Show",
    thumbnailUrl: "https://i.ytimg.com/vi/TnoZi5vL7Vk/hqdefault.jpg",
    channelId: "alainmoise",
    channelTitle: "Alain Moise",
    category: "swimwear",
    isFeatured: true,
    sortOrder: 4,
  },
  {
    youtubeId: "GyuzgNBmcgY",
    title: "Meduza Swimwear 4K | Fashion Runway Full Show",
    thumbnailUrl: "https://i.ytimg.com/vi/GyuzgNBmcgY/hqdefault.jpg",
    channelId: "alainmoise",
    channelTitle: "Alain Moise",
    category: "swimwear",
    isFeatured: false,
    sortOrder: 5,
  },
  {
    youtubeId: "6vVDtHJFXk4",
    title: "Veve Swimwear 4K | Fashion Runway Full Show",
    thumbnailUrl: "https://i.ytimg.com/vi/6vVDtHJFXk4/hqdefault.jpg",
    channelId: "alainmoise",
    channelTitle: "Alain Moise",
    category: "swimwear",
    isFeatured: false,
    sortOrder: 6,
  },
  {
    youtubeId: "G9eoxsUSa5E",
    title: "Capristan Swim Runway | Miami Art Basel Fashion Show",
    thumbnailUrl: "https://i.ytimg.com/vi/G9eoxsUSa5E/hqdefault.jpg",
    channelId: "alainmoise",
    channelTitle: "Alain Moise",
    category: "swimwear",
    isFeatured: false,
    sortOrder: 7,
  },
  {
    youtubeId: "QP7h6dc9YTc",
    title: "Fashion Runway Show",
    thumbnailUrl: "https://i.ytimg.com/vi/QP7h6dc9YTc/hqdefault.jpg",
    channelId: "alainmoise",
    channelTitle: "Alain Moise",
    category: "swimwear",
    isFeatured: false,
    sortOrder: 8,
  },
  {
    youtubeId: "Iu68o0MCuvw",
    title: "Fashion Runway Show",
    thumbnailUrl: "https://i.ytimg.com/vi/Iu68o0MCuvw/hqdefault.jpg",
    channelId: "alainmoise",
    channelTitle: "Alain Moise",
    category: "swimwear",
    isFeatured: false,
    sortOrder: 9,
  },
  {
    youtubeId: "v5MgC0YjLvw",
    title: "Fashion Runway Show",
    thumbnailUrl: "https://i.ytimg.com/vi/v5MgC0YjLvw/hqdefault.jpg",
    channelId: "alainmoise",
    channelTitle: "Alain Moise",
    category: "swimwear",
    isFeatured: false,
    sortOrder: 10,
  },
  {
    youtubeId: "9yInHSSOT20",
    title: "Fashion Runway Show",
    thumbnailUrl: "https://i.ytimg.com/vi/9yInHSSOT20/hqdefault.jpg",
    channelId: "alainmoise",
    channelTitle: "Alain Moise",
    category: "swimwear",
    isFeatured: false,
    sortOrder: 11,
  },
  {
    youtubeId: "9s8Z7NHfF8Y",
    title: "Fashion Runway Show",
    thumbnailUrl: "https://i.ytimg.com/vi/9s8Z7NHfF8Y/hqdefault.jpg",
    channelId: "alainmoise",
    channelTitle: "Alain Moise",
    category: "swimwear",
    isFeatured: false,
    sortOrder: 12,
  },
  {
    youtubeId: "Qxi9oHMvrH8",
    title: "Fashion Runway Show",
    thumbnailUrl: "https://i.ytimg.com/vi/Qxi9oHMvrH8/hqdefault.jpg",
    channelId: "alainmoise",
    channelTitle: "Alain Moise",
    category: "swimwear",
    isFeatured: false,
    sortOrder: 13,
  },
  {
    youtubeId: "lYzSnPZ-peE",
    title: "Fashion Runway Show",
    thumbnailUrl: "https://i.ytimg.com/vi/lYzSnPZ-peE/hqdefault.jpg",
    channelId: "alainmoise",
    channelTitle: "Alain Moise",
    category: "swimwear",
    isFeatured: false,
    sortOrder: 14,
  },
  {
    youtubeId: "aSo3-aF0ERQ",
    title: "Fashion Runway Show",
    thumbnailUrl: "https://i.ytimg.com/vi/aSo3-aF0ERQ/hqdefault.jpg",
    channelId: "alainmoise",
    channelTitle: "Alain Moise",
    category: "swimwear",
    isFeatured: false,
    sortOrder: 15,
  },
  {
    youtubeId: "72wRZWY8SRE",
    title: "Fashion Runway Show",
    thumbnailUrl: "https://i.ytimg.com/vi/72wRZWY8SRE/hqdefault.jpg",
    channelId: "alainmoise",
    channelTitle: "Alain Moise",
    category: "swimwear",
    isFeatured: false,
    sortOrder: 16,
  },
  {
    youtubeId: "bYzzNSEEKuM",
    title: "Fashion Runway Show",
    thumbnailUrl: "https://i.ytimg.com/vi/bYzzNSEEKuM/hqdefault.jpg",
    channelId: "alainmoise",
    channelTitle: "Alain Moise",
    category: "swimwear",
    isFeatured: false,
    sortOrder: 17,
  },
  {
    youtubeId: "LyMckCEBd4A",
    title: "Fashion Runway Show",
    thumbnailUrl: "https://i.ytimg.com/vi/LyMckCEBd4A/hqdefault.jpg",
    channelId: "alainmoise",
    channelTitle: "Alain Moise",
    category: "swimwear",
    isFeatured: false,
    sortOrder: 18,
  },
  {
    youtubeId: "ns1wW6t2ZQs",
    title: "Fashion Runway Show",
    thumbnailUrl: "https://i.ytimg.com/vi/ns1wW6t2ZQs/hqdefault.jpg",
    channelId: "alainmoise",
    channelTitle: "Alain Moise",
    category: "swimwear",
    isFeatured: false,
    sortOrder: 19,
  },
  {
    youtubeId: "lh-di3iX1uI",
    title: "Fashion Runway Show",
    thumbnailUrl: "https://i.ytimg.com/vi/lh-di3iX1uI/hqdefault.jpg",
    channelId: "alainmoise",
    channelTitle: "Alain Moise",
    category: "swimwear",
    isFeatured: false,
    sortOrder: 20,
  },
  {
    youtubeId: "m12eYGVc4Yg",
    title: "Fashion Runway Show",
    thumbnailUrl: "https://i.ytimg.com/vi/m12eYGVc4Yg/hqdefault.jpg",
    channelId: "alainmoise",
    channelTitle: "Alain Moise",
    category: "swimwear",
    isFeatured: false,
    sortOrder: 21,
  },
  {
    youtubeId: "IRWcdfdTc4k",
    title: "Fashion Runway Show",
    thumbnailUrl: "https://i.ytimg.com/vi/IRWcdfdTc4k/hqdefault.jpg",
    channelId: "alainmoise",
    channelTitle: "Alain Moise",
    category: "swimwear",
    isFeatured: false,
    sortOrder: 22,
  },
  {
    youtubeId: "zdeZhSIncXo",
    title: "Fashion Runway Show",
    thumbnailUrl: "https://i.ytimg.com/vi/zdeZhSIncXo/hqdefault.jpg",
    channelId: "alainmoise",
    channelTitle: "Alain Moise",
    category: "swimwear",
    isFeatured: false,
    sortOrder: 23,
  },
  {
    youtubeId: "pQvQFbLTzZM",
    title: "Fashion Runway Show",
    thumbnailUrl: "https://i.ytimg.com/vi/pQvQFbLTzZM/hqdefault.jpg",
    channelId: "alainmoise",
    channelTitle: "Alain Moise",
    category: "swimwear",
    isFeatured: false,
    sortOrder: 24,
  },
  {
    youtubeId: "9JDS57YIyb0",
    title: "Fashion Runway Show",
    thumbnailUrl: "https://i.ytimg.com/vi/9JDS57YIyb0/hqdefault.jpg",
    channelId: "alainmoise",
    channelTitle: "Alain Moise",
    category: "swimwear",
    isFeatured: false,
    sortOrder: 25,
  },
];

async function seedVideos() {
  console.log("Seeding videos...");

  for (const video of videosData) {
    try {
      await db
        .insert(videos)
        .values(video)
        .onConflictDoUpdate({
          target: videos.youtubeId,
          set: {
            title: video.title,
            thumbnailUrl: video.thumbnailUrl,
            isFeatured: video.isFeatured,
            sortOrder: video.sortOrder,
            updatedAt: new Date(),
          },
        });
      console.log(`✓ Added: ${video.title}`);
    } catch (error) {
      console.error(`✗ Failed: ${video.title}`, error);
    }
  }

  console.log("\nDone! Seeded", videosData.length, "videos");
  process.exit(0);
}

seedVideos();
